language: php
os: linux
dist: trusty
matrix:
  include:
    - language: php
      php: "7.4"
      services:
        - mysql  
      before_install:
        - mysql -u root --password="" < back-end/database/database.sql
        - mysql -u root --password="" appointment_booking_system  < back-end/database/test_data.sql
        - composer self-update
      before_script:
        - composer install
      script: vendor/bin/phpunit --configuration phpunit.xml --stderr

    # - language: node_js
    #   node_js: "node"
    #   services:
    #     - mysql
    #   addons:
    #     chrome: stable
    #   before_install:
    #     - npm i -g http-server
    #     - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    #   before_script:
    #     - npm i
    #     - http-server -p 80
    #     - sleep 3
    #   script: npm run test-headless
